first_name = input("Please enter your first name: ")
middle_initial = input("Please enter your middle initial: ")
last_name = input("Please enter your last name: ")
street_address = input("Please enter your street address: ")
city = input("Please enter your city: ")
state_abb = input("Please enter your state abbreviation: ")
zip_code = input("Please enter your zip code: ")
phone_number = input("Please enter a valid phone number: ")
email_address = input("Please enter a valid email address: ")
print("Please make sure all imformation is correctly inputed!")


print(f"{first_name} {middle_initial} {last_name}")
print(f"{street_address} {city} {state_abb} {zip_code}")
print (f"{phone_number} {email_address}")
